version: '3.8'

networks:
  review: 
    driver: bridge

services:
  review-service:
    image: wjd4204/review-service:latest
    container_name: review-service
    ports:
      - 8082:8080
    environment:
      DB_PASSWORD: ${DB_PASSWORD}
      DB_URL: ${DB_URL}
      DB_USERNAME: ${DB_USERNAME}
      EMAIL: ${EMAIL}
      EMAIL_PW: ${EMAIL_PW}
      JWT_SECRET: ${JWT_SECRET}
      CLIENT_ID: ${CLIENT_ID}
      GOOGLE_SECRET: ${GOOGLE_SECRET}
      S3_ACCESS_KEY: ${S3_ACCESS_KEY}
      S3_NAME: ${S3_NAME}
      S3_SECRET_KEY: ${S3_SECRET_KEY}
      REDIS_HOST: redis
      REDIS_PORT: 6379
    depends_on:
      - redis
    networks:
      - review

  customer-service:
    image: snhng/customer-service:latest
    container_name: customer-service
    ports:
      - 8083:8080
    platform: linux/amd64
    environment:
      DB_PASSWORD: ${DB_PASSWORD}
      DB_USERNAME: ${DB_USERNAME}
      DB_HOST: ${DB_HOST}
      DB_PORT: ${DB_PORT}
      DB_NAME: ${DB_NAME}
      ALADIN_KEY: ${ALADIN_KEY}
      KOFIC_KEY: ${KOFIC_KEY}
    networks:
      - review

  redis:
    image: redis:latest
    container_name: redis
    ports:
      - "6379:6379"
    networks:
      - review
